### ISSUE TITLE
[HELP] How to programatically add a varying amount of choices

### ISSUE THREAD

**Issue by aunefyren** [mroth/weightedrand#22]
Hey, was I wondering if I could get some help on how to utilize this package. Feel free to close this issue if it is out of place or obvious.

I need to add a varying amount of choices with different weights based on the context of the usage. So I obviously created a for loop, but I can't for the life of me use the `NewChoice()` command correctly. The chooser does not accept arrays and I am not sure on how I can add choices one by one to the same instance. I tried to create an array of `weightedrand.Choice` structs but the `NewChooser()` does not want them. 

Have I totally misunderstood or is this not possible? If it is possible, could I get an example?

Thank you so much for reading my issue.

**Comment by mroth** [comment]
Hi @aunefyren. the `NewChooser()` is a variadic function in Go, which means it can take an arbitrary number of parameters. So in this case,  the `NewChooser(choices ...Choice)` in the type signature means it can take zero to many Choice parameters as arguments.  This is fairly common in Go, an example would be the [`fmt.Println(a ...any)`](https://pkg.go.dev/fmt#Println) function from the standard library, where you can pass as many arguments of any type as you like to it.

In order to to pass a slice to a variadic function, use the `...` notation on the slice, for example:
```go
// a slice of choices
choices := []weightedrand.Choice{
    weightedrand.NewChoice("alpha", 1),
    weightedrand.NewChoice("beta", 2),
    weightedrand.NewChoice("gamma", 3),
}

chooser := weightedrand.NewChooser(choices...) // <-- note the ... syntax which "expands" the slice into parameters
``` 

See also https://gobyexample.com/variadic-functions

Feel free to re-open if this doesn't clear it up!

**Comment by aunefyren** [comment]
Thank you so much for your help, worked like a charm :)
